# Copyright (c) 2016-2024 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
# 주석:좌상단 텍스트
# site_name: Material for MkDocs
site_name: 나의 해방 일지
site_url: http://bluesnite.xyz/
site_author: Jeong Ji Min
site_description: >-
  나의 작은 해방 일지, 내가 해방되는 그날까지 ...
# Write your documentation in Markdown and create a professional static site in
# minutes – searchable, customizable, in 60+ languages, for all devices

# Repository 주석:본문 깃헙에디터링크연결
#repo_name: squidfunk/mkdocs-material
#repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
copyright: Copyright &copy; 2023 - 2024 Jeong Ji Min

# Configuration
theme:
  name: material
  language: ko
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand # 네비게이션확장
    - navigation.footer
    - navigation.indexes # 폴더 인덱스 카테고리 표기
    - navigation.instant # 인스턴트 프리페치
    # - navigation.instant.prefetch # 인스턴트 프리페치 (별로인듯)
    - navigation.instant.progress # 인스턴트 진행률 표시기
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate # 우측 목차 네비로 병합
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  #주석:폰트
  font:
    text: Sans Pro
    code: Sans Pro
  #주석:파비콘
  # favicon: stylesheets/assets/icon2.png
  favicon: stylesheets/assets/favicon10.png
  icon:
    logo: logo

# Plugins
plugins:
  #- blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - regex_filter
  # - mkdocs-simple-hooks:
  # hooks:
  # on_config: "hooks:on_config"
#  - minify:
#      minify_html: true

extra_javascript:
  - stylesheets/extra.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/tailwind.css

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    # 주석:최하단 어플리케이션 아이콘
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/
    - icon: fontawesome/brands/python
      link: https://pypi.org/
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/

# Extensions
markdown_extensions:
  - custom_extensions.obsidian_callouts
  - custom_extensions.obsidian_images
  - custom_extensions.obsidian_root_images
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

not_in_nav: |
  /tutorials/**/*.md

nav:
  - Home: index.md
  - 1. 개발 및 배포 도구:
      - 1. 개발 및 배포 도구/index.md
      - argocd:
          - Argocd 성능개선: 1. 개발 및 배포 도구/argocd/Argocd-성능개선.md
      - docker:
          - 도커 설치: 1. 개발 및 배포 도구/docker/도커 설치.md
          - 도커 사용을 편리하게: 1. 개발 및 배포 도구/docker/도커 사용을 편리하게.md
      - gitlab:
          - gitlab 서로다른 레포지토리 병합 미러링: 1. 개발 및 배포 도구/gitlab/gitlab 서로다른 레포지토리 병합 미러링.md
      - jenkins:
          - 젠킨스 agent: 1. 개발 및 배포 도구/jenkins/젠킨스 agent.md
          - 젠킨스 rebuild 후속작업: 1. 개발 및 배포 도구/jenkins/젠킨스 rebuild 후속작업.md
          - 젠킨스 슬랙: 1. 개발 및 배포 도구/jenkins/젠킨스 슬랙.md
          - 젠킨스 Role-Based Authorization Strategy: 1. 개발 및 배포 도구/jenkins/젠킨스 Role-Based Authorization Strategy.md
      - kubernetes:
          - 쿠버 Argocd설치: 1. 개발 및 배포 도구/kubernetes/쿠버 Argocd설치.md
          - 쿠버 CNI의 종류: 1. 개발 및 배포 도구/kubernetes/쿠버 CNI의 종류.md
          - 쿠버 Istio gateway 설정: 1. 개발 및 배포 도구/kubernetes/쿠버 Istio gateway 설정.md
          - 쿠버 MetalLB 세팅이슈: 1. 개발 및 배포 도구/kubernetes/쿠버 MetalLB 세팅이슈.md
          - 쿠버-리디렉션이슈: 1. 개발 및 배포 도구/kubernetes/쿠버-리디렉션이슈.md
          - 쿠버-퍼드 생성 연습: 1. 개발 및 배포 도구/kubernetes/쿠버-퍼드 생성 연습.md
      - nexus:
          - NEXUS Disk 관리: 1. 개발 및 배포 도구/nexus/NEXUS Disk 관리.md
          - NEXUS-설치: 1. 개발 및 배포 도구/nexus/NEXUS-설치.md
      - sonarqube:
          - SonarQube 설치 및 통합 가이드: 1. 개발 및 배포 도구/sonarqube/SonarQube 설치 및 통합 가이드.md
  - 2. 운영체제 및 서버 관리:
      - 2. 운영체제 및 서버 관리/index.md
      - certbot:
          - Let's encrypt: 2. 운영체제 및 서버 관리/certbot/Let's encrypt.md
      - linux:
          - linux-xrdp 설정: 2. 운영체제 및 서버 관리/linux/linux-xrdp 설정.md
          - linux-자동완성기능: 2. 운영체제 및 서버 관리/linux/linux-자동완성기능.md
      - nginx:
          - Nginx conf 옵션확인: 2. 운영체제 및 서버 관리/nginx/Nginx conf 옵션확인.md
          - Nginx Log 관리하기: 2. 운영체제 및 서버 관리/nginx/Nginx Log 관리하기.md
          - Nginx 설정 테스트 및 재시작: 2. 운영체제 및 서버 관리/nginx/Nginx 설정 테스트 및 재시작.md
      - qemu-kvm:
          - kvm containerd 디스크 문제 해결 방법: 2. 운영체제 및 서버 관리/qemu-kvm/kvm containerd 디스크 문제 해결 방법.md
          - kvm 명령어: 2. 운영체제 및 서버 관리/qemu-kvm/kvm 명령어.md
          - kvm 아이피 확인절차: 2. 운영체제 및 서버 관리/qemu-kvm/kvm 아이피 확인절차.md
      - ubuntu:
          - ubuntu desktop install: 2. 운영체제 및 서버 관리/ubuntu/ubuntu desktop install.md
      - window:
          - powershell에서 디렉토리 트리보기: 2. 운영체제 및 서버 관리/window/powershell에서 디렉토리 트리보기.md
  - 3. 데이터 관리:
      - 3. 데이터 관리/index.md
      - mysql:
          - Mysql-설치: 3. 데이터 관리/mysql/Mysql-설치.md
      - opensearch:
          - 오픈서치-knn설정: 3. 데이터 관리/opensearch/오픈서치-knn설정.md
          - 오픈서치-대시보드 구성 요령: 3. 데이터 관리/opensearch/오픈서치-대시보드 구성 요령.md
          - 오픈서치-설치: 3. 데이터 관리/opensearch/오픈서치-설치.md
          - 오픈서치 HA: 3. 데이터 관리/opensearch/오픈서치 HA.md
      - postgres:
          - PostgreSQL CLI로 설치하고 접속확인까지: 3. 데이터 관리/postgres/PostgreSQL CLI로 설치하고 접속확인까지.md
          - PostgreSQL-설치: 3. 데이터 관리/postgres/PostgreSQL-설치.md
  - 4. 모니터링 및 시각화:
      - 4. 모니터링 및 시각화/index.md
      - grafana:
          - grafana-panels 모음: 4. 모니터링 및 시각화/grafana/grafana-panels 모음.md
      - jconsole:
          - Jconsole to Local: 4. 모니터링 및 시각화/jconsole/Jconsole to Local.md
      - sampler:
          - sampler-설치: 4. 모니터링 및 시각화/sampler/sampler-설치.md
      - scouter:
          - scouter-설치: 4. 모니터링 및 시각화/scouter/scouter-설치.md
      - superset:
          - Superset을 Terraform Docker로 설치해보았다: 4. 모니터링 및 시각화/superset/Superset을 Terraform Docker로 설치해보았다.md
  - 5. 클라우드 및 인프라:
      - 5. 클라우드 및 인프라/index.md
      - aws:
          - AWS EC2에 SSH 접속하기 위한 최소작업: 5. 클라우드 및 인프라/aws/AWS EC2에 SSH 접속하기 위한 최소작업.md
          - AWS 다른나라 리전에서 한국사이트 접속: 5. 클라우드 및 인프라/aws/AWS 다른나라 리전에서 한국사이트 접속.md
          - AWS-EKS 자격증명하기: 5. 클라우드 및 인프라/aws/AWS-EKS 자격증명하기.md
      - IaC:
          - Terraform provisioner 사용방법: 5. 클라우드 및 인프라/IaC/Terraform provisioner 사용방법.md
          - Terraform `user_data` 사용 및 로그확인: 5. 클라우드 및 인프라/IaC/Terraform `user_data` 사용 및 로그확인.md
          - Terraform 변수 정의하기: 5. 클라우드 및 인프라/IaC/Terraform 변수 정의하기.md
          - Terraform 설치 후 테스트: 5. 클라우드 및 인프라/IaC/Terraform 설치 후 테스트.md
  - 6. 개인 및 블로그 관리:
      - 6. 개인 및 블로그 관리/index.md
      
      - 블로그:
          - 블로그 호스팅: 6. 개인 및 블로그 관리/블로그/블로그 호스팅 1편 - quartz.md
          - 블로그 이관: 6. 개인 및 블로그 관리/블로그/블로그 호스팅 2편 - mkdocs.md
      - 생각:
          - 스토리 포인트는 무의미하다의 글: 6. 개인 및 블로그 관리/생각/스토리 포인트는 무의미하다의 글.md
          - 옳은 종류의 고집: 6. 개인 및 블로그 관리/생각/옳은 종류의 고집.md
      - 옵시디언:
          - 플러그인 - Execute Code: 6. 개인 및 블로그 관리/옵시디언/플러그인 - Execute Code.md
      - 추천글:
          - 갈때를 아는 방법: 6. 개인 및 블로그 관리/추천글/갈때를 아는 방법.md
      - 학습:
          - 내가 학습한 워크플로우: 6. 개인 및 블로그 관리/학습/내가 학습한 워크플로우.md
      - 내소개:
          - 내 소개: 6. 개인 및 블로그 관리/내소개/내 소개.md
